---
apiVersion: v1
kind: Service
metadata:
  name: mygott-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mygott
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygott
  namespace: default
spec:
  selector:
    matchLabels:
      app: mygott
  replicas: 1
  template:
    metadata:
      labels:
        app: mygott
    spec:
      containers:
        - name: jtproxy
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
